name: mdproj

channels:
  - conda-forge
  - memex
  - anaconda
  
dependencies:
    - scipy
    - numexpr >=2.4
    - scikit-learn >=0.16.1
    - cherrypy
    - joblib
    - functools32
    - jinja2
    - nodejs
    - dateutil
    - elasticsearch
    - pyelasticsearch >=1.2
    - nltk
    - futures